language: php
php:
  - '7.4'

jobs:
  include:
    - stage: Install dependencies
      script: composer install --no-progress --no-interaction --optimize-autoloader

    - stage: Static Analyis
      script: composer static-analysis

    - stage: Tests
      script: composer test
