language: php
php:
  - '7.4.9'
before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install php7.4-curl
install: composer install --no-progress --no-interaction --optimize-autoloader
before_script: php -i
script:
  - composer static-analysis
  - composer test
