language: php
php:
  - '7.4'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y php7.4-curl
install: composer install --no-progress --no-interaction --optimize-autoloader
script:
  - composer static-analysis
  - composer test
